### ISSUE TITLE
Mark set doesn't seem to work.

### ISSUE THREAD

**Issue by saolsen** [nightwing/cm6-emacs-experiment#14]
Using Ctrl-Space to set the mark, and moving the cursor around should highlight the code between the mark and the cursor, I see code for that keybinding in the plugin but it doesn't seem to work on any of the sites that use the plugin including repl.it.

**Comment by nightwing** [comment]
Should be fixed with the linked pull request

**Comment by saolsen** [comment]
Awesome, are you going to do an npm release for the fix?

**Comment by nightwing** [comment]
@masad-frost could you publish the new version to npm.

**Comment by masad-frost** [comment]
Published 6.1.0
